name: CI Java App
on:
  push:
    branches: [ "github-actions" ]
  pull_request:
    branches: [ "github-actions" ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Lint the code
        uses: super-linter/super-linter@v5
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: github-actions
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
